# theme: jekyll-theme-cayman

# remote_theme: mmistakes/minimal-mistakes
#minimal_mistakes_skin: air # “air”, “aqua”, “contrast”, “dark”, “dirt”, “neon”, “mint”, “plum”, “sunrise”

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
